services:
  marketbw:
    container_name: marketbw-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - marketbw-stack-net
    volumes:
      - ../data:/app/data

networks:
  marketbw-stack-net:
    driver: bridge
    name: marketbw-stack-net